---
- name: EPEL repository is available
  yum:
    name: epel-release
  tags: packages

- name: redis is installed
  yum:
    name: redis

- name: redis is started a ready to survive restarts
  service:
    name: redis
    state: started
    enabled: yes
